### ISSUE TITLE
args are not working

### ISSUE THREAD

**Issue by lucaorio** [SublimeLinter/SublimeLinter-html-tidy#12]
It seems that the args are not working for this linter.
Am I doing anything wrong?

``` json
"htmltidy": {
    "@disable": false,
    "args": [
        "--drop-proprietary-attributes=yes"
    ],
    "excludes": []
},
```

**Comment by cafesanu** [comment]
This might help: http://stackoverflow.com/questions/22273774/st3-sublimelinter-with-html-tidy-doesnt-obey-args

**Comment by cafesanu** [comment]
This worked for me on the sublime setting
"linters": {
            "htmltidy": {
                "@disable": false,
                "args": [
                //http://tidy.sourceforge.net/docs/quickref.html
                    "--drop-proprietary-attributes", "false"
                ],
                "excludes": []
            },...

**Comment by Aedx** [comment]
@cafesanu This issue has been closed for almost a year, and was solved. Please read the comments in this issue – the problems were not of incorrectly formatted JSON, but rather the misunderstanding of the purpose of an argument and the way in which arguments are passed. Please do not bump old issues such as this without reading them first.
