### ISSUE TITLE
How I can install windows binary tidy.exe

### ISSUE THREAD

**Issue by dimaMachina** [SublimeLinter/SublimeLinter-html-tidy#13]
How I can install Windows binary tidy.exe on Windows 8
When I open tidy.exe from http://tidybatchfiles.info/ , I get it and that's all

https://www.dropbox.com/s/5wpjt3dmzzes4t2/tidy.png

**Comment by thorade** [comment]
Maybe add to the docs that `tidy.exe` is needed (not `tidy.dll` or anything else).
And a reminder about `echo %PATH%` from cmd to see all locations already on path.
And, after adding new path to PATH, a restart might be required.
