### ISSUE TITLE
How to use tidy-html5 instead of tidy?

### ISSUE THREAD

**Issue by aristidesfl** [SublimeLinter/SublimeLinter-html-tidy#22]
Here is a 3rd party homebrew formula to install tidy-html5 as tidy-html5 binary: https://gist.githubusercontent.com/steakknife/7f6dc60b1a4b4e9d12c6/raw/tidy-html5.rb

Is there a way to configure SublimLinter-html-tidy to use tidy-html5 instead of tidy, without having to install tidy-html5 as tidy?

Thanks

**Comment by skj3gg** [comment]
You could clone this repository into the `Packages` directory and change cmd variable. You may need to change the regular expression in `regex` to match a different output, but don't know.

**Comment by aristidesfl** [comment]
SublimeLinter plugins can't have configuration variables?

**Comment by skj3gg** [comment]
They can, this doesn't. This is open source, so feel free to contribute this setting.

**Comment by aristidesfl** [comment]
This won't be necessary after all. It seems the html5 version can be easily installed with `brew install homebrew/dupes/tidy --HEAD`

Should I add this info to the README or you do it?

**Comment by skj3gg** [comment]
feel free to add it.
