### ISSUE TITLE
Path setup in Sublime Text 2

### ISSUE THREAD

**Issue by mohanr** [SublimeLinter/SublimeLinter-html-tidy#25]
I have installed Tidy. And then installed this linter.

After that according to http://sublimelinter.readthedocs.org/en/latest/troubleshooting.html#finding-a-linter-executable I need to set the path to Tidy in Sublime User settings.

```JSON
{
    "paths": {
        "linux": [],
        "osx": [
            "~/.rbenv/shims"
        ],
        "windows": []
    }
}
```

I am assuming these are the correct steps.

My Sublime User settings already has this.

```JSON
{
    "ignored_packages":
    [
        "Vintage"
    ]
}
```

Does anyone know where in this the new 'paths' should be added ?

**Comment by Aedx** [comment]
Could you tell me which OS that you are using please?

**Comment by Aedx** [comment]
Closing because no updates have taken place in over a month.
