### ISSUE TITLE
Error with Sublime Linter HTML Tidy

### ISSUE THREAD

**Issue by laffy777** [SublimeLinter/SublimeLinter-html-tidy#28]
Hey there, first of all, as a beginner programmer, your service is the coolest thing ever!  

However, the HTML sublimelinter isn't working, and from the console:
SublimeLinter/lint/linter.py", line 1582, in can_lint
    status = 'WARNING: {} deactivated, cannot locate \'{}\''.format(cls.name, executable)

What should I do?

**Comment by Aedx** [comment]
Do you have tidy/tidy5 installed on your system? Also, does this error message occur with any other linter, or even with no linter installed whatsoever?

**Comment by Aedx** [comment]
Do you have any updates on this issue?

**Comment by skj3gg** [comment]
Closing this but will reopen if new data is presented. Hoping you figured out your issue!
