### ISSUE TITLE
tidy5 is not found on OS X with shutil.which

### ISSUE THREAD

**Issue by therealmarv** [SublimeLinter/SublimeLinter-html-tidy#31]
This line will not find homebrewed installed tidy5. It also does not find my npm installed linters (but they work):
https://github.com/SublimeLinter/SublimeLinter-html-tidy/blob/3db0b3975edf8b1e3c2a18e44a28d374702cc20d/linter.py#L22

It works generally different than OS X internal `which` on commandline.
Related link to the problem http://bugs.python.org/issue17012 :/

**Comment by therealmarv** [comment]
It seems this is an internal bug of ST3 which uses Python 3.3.3:
![image](https://cloud.githubusercontent.com/assets/1050582/8021498/402725e2-0ca2-11e5-976d-eadbdbd37e4b.png)

It works on my internal Python 3.4.3 though:  
```
$ python3
Python 3.4.3 (default, Jun  1 2015, 09:58:35)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import shutil
>>> shutil.which('tidy5')
'/usr/local/bin/tidy5'
>>>
```

So this bug needs maybe need to be submitted upstream to ST3 itself ;)

**Comment by Aedx** [comment]
What are the results of adding `"/usr/local/bin/"` to `.user.paths.osx[]` in `Preferences -> Package Settings -> SublimeLinter -> Settings - User`? Also, is your `/usr/`, `/usr/local/` or `/usr/local/bin/` symlinked to another directory (find out with `ls -al`, the filename should have 'lrwxrwxrwx' at the beginning of its line)? I've never used OS X, but I think that Apple do something weird with the *nix paths.

**Comment by therealmarv** [comment]
`.user.paths.osx[]` has no effect in finding `tidy5`. Files in `/usr/local/bin` are symlinked to the Homebrew binaries but this should not be a problem because all other linters which use homebrew also work. I also tested Python 3.3.3 itself and it can find `tidy5`.
So it seems `shutil.which` is not reliable in OS X in Sublime Text (it works on a standalone Python though).
I made a fork and will try if I can get an alternative approach of finding the binary on ST3 and OS X.

**Comment by Aedx** [comment]
Does the plugin still properly load the old tidy executable?

**Comment by therealmarv** [comment]
yes this works all the time.

**Comment by therealmarv** [comment]
I've boiled the problem down now. When I start ST3 from the OS X dock the `PATH` environment does not point to the homebrew paths and all other paths. It only points to this paths when I start ST3 from commandline. So `shutil.which` is dependent on how ST3 is started. But I've found another `which` from SublimeLinter3 itself which does the job right! See here:
http://www.sublimelinter.com/en/latest/linter_methods.html?highlight=executable_path#which

Sending PR.

**Comment by therealmarv** [comment]
May you please also add a new tag/release for notification that packagecontrol.io should update the version? Thank! :)

**Comment by Aedx** [comment]
Hmm, I always thought that packagecontrol.io automatically updated. Apparently not. Sorting this out.

**Comment by therealmarv** [comment]
works now from Packagecontrol :raised_hands:
