### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by joelataylor** [SublimeLinter/SublimeLinter-html-tidy#38]
I followed the instructions, but still don't know how to actually _run_ the tidy command on a selected html. This command isn't in the readme. Help?

**Comment by kasi1999999** [comment]
Same as @joelataylor , how can I run the _tidy_ command?

**Comment by bolandross** [comment]
Same as @joelataylor and @kasi1999999 , how can we run the _tidy_ command??

**Comment by gazsp** [comment]
+1

**Comment by braver** [comment]
The “Lint this view” command will run tidy.
