### ISSUE TITLE
Suppress some warnings with ignore_match?

### ISSUE THREAD

**Issue by franciscolourenco** [SublimeLinter/SublimeLinter-html-tidy#39]
I'm trying to suppress "proprietary attribute" warnings with the `ignore_match` preference.
It's not working, any idea what I'm doing wrong? 
This is my user preference file: https://gist.github.com/aristidesfl/90701018e29eee378fb7

Thanks!

**Comment by aristidesfl** [comment]
ping, there seems to be a bug here

**Comment by itsgg** [comment]
@aristidesfl Add full messages

```json
                "ignore_match": [
                    "missing <!DOCTYPE> declaration",
                    "content occurs after end of body",
                    "<template> proprietary attribute \"name\""
                ]

```

**Comment by aristidesfl** [comment]
@itsgg thanks, that seems to work, however it seems unreasonable to have to add a ignore_match entry for each new proprietary attribute. Regex matching should be added, do you agree?

**Comment by morenopc** [comment]
`ignore_match` is not working but other settings are. Can somebody give me a clue? (Sublime 3.1.1 and SublimeLinter-html-tidy v2.0.0)
```
// SublimeLinter Settings - User
{
    "linters":{
        "htmltidy": {
                    "disable": false,
                    "args": [
                        "--show-warnings",
                        "true"
                    ],
                    "excludes": [],
                    "ignore_match": [
                        "missing <!DOCTYPE> declaration",
                        "content occurs after end of body",
                        "<template> proprietary attribute \"name\""
                    ]
                }
    }
}
```

**Comment by kaste** [comment]
Sorry, needs to be reimplemented. PRs very welcome. 

I can explain how it can be implemented. But since a PR needs testing and the small details I cannot actually do the PR.

**Comment by morenopc** [comment]
Seems like it have been removed on version 4:

> The settings "ignore_matches" and "demote_to_warning_matches" have been removed.
> Your linter should have settings to modify the rules or severity levels.

https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0.txt

**Comment by kaste** [comment]
Okay, you have a python shirt, 🤷‍♂️  so it's really easy.

Override the method `find_errors(output)` to something like that.

```
def find_errors(self, output):
	ignore = self.get_view_settings().get('however-we-call-this', [])
	return (error for error in super().find_errors(output) if error['msg'] is okay)
```

Probably would be good if the ignore_matches were a list of regexes.

**Comment by braver** [comment]
@morenopc 

- uninstall SL-html-tidy via package control
- open the Packages directory 
- clone your fork of this repo into it

All changes you make should result in Sublime reloading the plugin immediately. Open the console to view the output.

**Comment by kaste** [comment]
This will be fixed/implemented upstream via https://github.com/SublimeLinter/SublimeLinter/pull/1424
