### ISSUE TITLE
<app-root> is not recognized! Did you mean to enable the custom-tags option?

### ISSUE THREAD

**Issue by zymr-keshav** [SublimeLinter/SublimeLinter-html-tidy#47]
I am using this plugin with sublime text 3 in Mac OS 10.1.3.1 and building an angular app where custom tags are inserted into the HTML file but it always gives error while saving the HTML file.
 
I have **`<app-root>`** tag in index.html and it gives error

> `<app-root>` is not recognized! Did you mean to enable the custom-tags option?

how to disable this error? DO I need to set all custom tags list inside sublime linter settings or is there any global settings for that?
Kindly help.

**Comment by kaste** [comment]
AFAIK you must set `--custom-tags true` on the command line. This can be done via the `args` setting within SublimeLinter. Pretty sure *tidy* also accepts config files, but don't know OTOH how this would look like..

**Comment by zymr-keshav** [comment]
but args accept array not string in **sublimeLinter.sublime-settings** file

tried
```
"htmltidy": {
                "@disable": false,
                "args": "--custom-tags true",
                "excludes": [],
                "ignore_match": [
                    "missing <!DOCTYPE> declaration",
                    "trimming empty",
                    ".*proprietary attribute",
                    "inserting (?:implicit <body>|missing 'title' element)"
                ]
            }
```
but stopped working everything
 also tried 

  `"args": ["--custom-tags true"]` but no success

**Comment by kaste** [comment]
Yes, `args` takes an array. `["--custom-tags", "true"]`

**Comment by zymr-keshav** [comment]
now it gives the error

> SublimeLinter: htmltidy: index.html ['/usr/local/bin/tidy', '-errors', '-quiet', '-utf8', '--custom-tags', 'true'] 
> SublimeLinter: htmltidy output:
> Document: "true" is not a file!

**Comment by kaste** [comment]
Yeah, okay, but what is actually the command you would run from your command line?

**Comment by minikN** [comment]
You have to set it like this  "args": `[ "--custom-tags true",]`
