### ISSUE TITLE
Html Code Error detect Is not working

### ISSUE THREAD

**Issue by zitengine** [SublimeLinter/SublimeLinter-html-tidy#48]
"linters": {
            "csslint": {
                "@disable": false,
                "args": [],
                "errors": "",
                "excludes": [],
                "ignore": "",
                "warnings": ""
            },
            "htmltidy": {
                "@disable": false,
                "args": [
                    "C:/tidy5/bin"
                ],
                "excludes": [
                    "C:/tidy5/bin"
                ]
            },
            "jshint": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "php": {
                "@disable": false,
                "args": [],
                "excludes": [
                    "C:/laragon/bin/php/php-7.2.1-Win32-VC15-x64"
                ]
            }
        },

SublimeLinter: php activated: C:\laragon\bin\php\php-7.2.1-Win32-VC15-x64\php.exe 
SublimeLinter: jshint version query: C:\Users\Abhay\AppData\Roaming\npm\jshint.cmd --version 
SublimeLinter: jshint version: 2.9.5 
SublimeLinter: jshint: (>= 2.5.0) satisfied by 2.9.5 
SublimeLinter: jshint activated: C:\Users\Abhay\AppData\Roaming\npm\jshint.cmd 
SublimeLinter: WARNING: htmltidy deactivated, cannot locate '' 
SublimeLinter: csslint version query: C:\Users\Abhay\AppData\Roaming\npm\csslint.cmd --version 
SublimeLinter: csslint version: 1.0.4 
SublimeLinter: csslint: (>= 0.10) satisfied by 1.0.4 
SublimeLinter: csslint activated: C:\Users\Abhay\AppData\Roaming\npm\csslint.cmd 
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2018-01-26 23:43:36, next run at 2018-01-27 00:43:36 or after

SublimeLinter: php: index.html ['C:\\laragon\\bin\\php\\php-7.2.1-Win32-VC15-x64\\php.exe', '-l', '-n', '-d', 'display_errors=On', '-d', 'log_errors=Off'] 
SublimeLinter: php output:
No syntax errors detected in Standard input code 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x00000251A0086990> 
SublimeLinter: php: index.html ['C:\\laragon\\bin\\php\\php-7.2.1-Win32-VC15-x64\\php.exe', '-l', '-n', '-d', 'display_errors=On', '-d', 'log_errors=Off'] 
SublimeLinter: php output:
No syntax errors detected in Standard input code 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x00000251A0086990>

**Comment by braver** [comment]
Why do you put the executable paths in the args setting?

**Comment by kaste** [comment]
Closing due to age
