### ISSUE TITLE
Recent Update throughs error

### ISSUE THREAD

**Issue by botweb** [SublimeLinter/SublimeLinter-html-tidy#51]
Using latest Sublime + Windows 10

> SublimeLinter: #2182 htmltidy module.php ERROR:
> 
>  Linter crashed.
> 
> Traceback (most recent call last):
>   File "lint.backend in D:\btsync\programs\sublime\Data\Installed Packages\SublimeLinter.sublime-package", line 97, in execute_lint_task
>   File "lint.linter in D:\btsync\programs\sublime\Data\Installed Packages\SublimeLinter.sublime-package", line 759, in lint
>   File "lint.linter in D:\btsync\programs\sublime\Data\Installed Packages\SublimeLinter.sublime-package", line 464, in get_cmd
>   File "linter in D:\btsync\programs\sublime\Data\Installed Packages\SublimeLinter-html-tidy.sublime-package", line 31, in cmd
> TypeError: which() missing 1 required positional argument: 'cmd'

**Comment by kaste** [comment]
This has been resolved via #50.

**Comment by botweb** [comment]
Works, thanks!
