### ISSUE TITLE
Is there an easy way to revert to the previous version?

### ISSUE THREAD

**Issue by displayadrian** [SublimeLinter/SublimeLinter-html-tidy#52]
Can anyone tell me if there's an easy way to manually install version 1.1.0 on Mac?

The loss of ignore_match in Sublime Linter 4 is a great tragedy in my life.

Thanks in advance.

**Comment by kaste** [comment]
What can't you do with http://api.html-tidy.org/tidy/tidylib_api_5.2.0/tidy_config.html you could do with `ignore_match`?

**Comment by displayadrian** [comment]
Tried and failed to configure it from tidy's end unfortunately. Not sure if that's me being daft or if it's down to actual limitations of the software or a bit of both. Feedback on their forum suggests that it's not possible to have the same level of control as we had with ignore_match:

> it can not ignore what it sees as an invalid URI in a href... you can use --fix-uri no to tell it to leave it alone, but it has to warn that it is not yet valid...

Am I right in thinking that version 2.0.0 of SublimeLinter-html-tidy is not compatible with SublimeLinter 3?

**Comment by kaste** [comment]
How do your Uris look like that you want to ignore the error?

**Comment by displayadrian** [comment]
Tracking tags are our main problem:

![image 2018-03-20 at 3 29 08 pm](https://user-images.githubusercontent.com/32849679/37664696-ba2eb5d4-2c53-11e8-9736-544981576d00.png)

Similar situation with these warnings:

![image 2018-03-20 at 3 31 57 pm](https://user-images.githubusercontent.com/32849679/37664841-e7a7e2b0-2c53-11e8-8ca4-654e2900fce3.png)

For our purposes, we think of these as false positives and they leave our document littered with warnings. Actual problems which need attention are lost amongst these, effectively rendering the linter useless.

**Comment by displayadrian** [comment]
I should have mentioned - we use Sublime primarily for building emails, so we have tables throughout our documents

**Comment by kaste** [comment]
May I ask why use html tidy at all for such a use case. Emails usually have very sloppy html, and html tidy is usually very strict.

I'm not super convinced here but the implementation here would be trivial, like 15 minutes, and a PR would be interesting enough.

**Comment by displayadrian** [comment]
With a bit of customisation, Tidy + SublimeLinter was a great system for checking email code. Simple mistakes such as missing image dimensions, broken table structure and unclosed spans could be seen at a glance.

We removed SublimeLinter 4 via Package Control and manually installed version 3 in order to revert to our previous setup. This was fine at first but that too stopped working, so I'm guessing that SublimeLinter-html-tidy 2.0.0 has dropped support for SL3.

**Comment by kaste** [comment]
Not intentionally, but generally if you pin SL to a previous version, you should pin aka manual install all the linters as well.

**Comment by displayadrian** [comment]
Ok, that makes sense. Manually installing SublimeLinter 3 was a simple case of dropping the folder into the Packages directory but I understand that it's not so simple to manually install the linter itself.

Any easy way to install the old version using the source code files from here?

https://github.com/SublimeLinter/SublimeLinter-html-tidy/archive/1.1.0.zip

**Comment by kaste** [comment]
It's the same for the linter plugins. Each into their own folder. Here SublimeLinter-html-tidy. It's even easier if you just git clone the repository and then check out a tag.

**Comment by displayadrian** [comment]
Superb, that's my problem solved. Thanks for the help.

**Comment by kaste** [comment]
Hey, c'mon, try a PR ❤️

**Comment by displayadrian** [comment]
I'd love to but I'm not familiar with Github to be honest and have no idea what's involved in that. I'll read up

**Comment by kaste** [comment]
This will be fixed/implemented upstream via SublimeLinter/SublimeLinter#1424
