### ISSUE TITLE
URL for binaries

### ISSUE THREAD

**Issue by thorade** [SublimeLinter/SublimeLinter-html-tidy#54]
HTML Tidy (now?) has a page for downloading the binaries:
http://binaries.html-tidy.org/
Maybe point to that instead of
http://tidybatchfiles.info/

**Comment by kaste** [comment]
Hm, can you make a PR? Although it seems that the official page has outdated versions only.

**Comment by thorade** [comment]
OK, strange, don't know where they found a 5.7 release?
https://github.com/htacg/tidy-html5/releases
They list 5.6 as latest release.
https://github.com/htacg/tidy-html5/releases/latest

**Comment by kaste** [comment]
master is 5.7.16

**Comment by thorade** [comment]
It seems 5.7 is not yet released and the version on master is currently in development? Should I ask for clarification in their issue tracker? Or ask tidybatchfiles.info how they built their binary?

**Comment by kaste** [comment]
Pretty sure you can ask them. tidy maintainer is super nice.

**Comment by braver** [comment]
I don't know what's up, but the "old" link still works and has newer release than the "new" link. I'm up for a PR if someone really wants to change something, but it doesn't seem worth it right now.
