### ISSUE TITLE
htmltidy: Defining 'cls.syntax' has no effect anymore.

### ISSUE THREAD

**Issue by leem32** [SublimeLinter/SublimeLinter-html-tidy#56]
I'm getting a deprecation warnng in Sublime text messages panel.

```
SublimeLinter: ERROR:
=====================

htmltidy: Defining 'cls.syntax' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.


SublimeLinter: ERROR:
=====================

htmltidy disabled. 'cls.defaults' is mandatory and MUST be a dict.

```

I found the same issue with another sublime linter plugin.
https://github.com/SublimeLinter/SublimeLinter-rubocop/issues/58

**Comment by braver** [comment]
Hm, we already prepared it for that deprecation, but apparently forgot to release it. 3.0.0 of the htmltidy plugin is out now and should fix this.
